name = "Callisto"
authors = ["Sanjay Lall <sanjaylall@google.com>"]
uuid = "4ae4e7f3-3a0d-47fd-9705-768e0f1baff0"
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"


